### ISSUE TITLE
StatefulSet is not working well with pdb minAvailable

### ISSUE THREAD

**Issue by hochuenw** [kubernetes-retired/kube-batch#195]
step to reproduce:
cluster can run 3 pods. whatever replicas I have in the replica set yaml file, as long as pdb min available is larger than 1. cluster can not run pods.

pdb.yaml 
```
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pdb-01
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nginx
```

ss.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      schedulerName: kube-batchd
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        resources:
          limits:
            memory: "3Gi"
            cpu: "3"
          requests:
            memory: "3Gi"
            cpu: "3"
```
