### ISSUE TITLE
Make plugins & actions configurable 

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#263]
kube-arbitrator has several plugins and actions currently, and all those plugins & actions should be configurable to meet different biz requirement.

**Comment by k82cn** [comment]
Here's an example of scheduler configuration, I'll open a PR for that :)

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kar-scheduler-conf
  namespace: kube-system
data:
  actions: decorate, allocate, preempt
  plugins: gang, priority, drf

  plugin.priority.preemptable: force
  plugin.priority.joborder: true
  plugin.priority.taskorder: true

  plugin.drf.preemptable: required
  plugin.drf.joborder: true

  plugin.gang.jobready: true
  plugin.gang.joborder: true
  plugin.gang.preemptable: required
```
