### ISSUE TITLE
QueueJob yaml problem in Tutorial 

### ISSUE THREAD

**Issue by DylanBLE** [kubernetes-retired/kube-batch#317]
I created a QueueJob follow the instruction of [Tutorial](https://github.com/kubernetes-incubator/kube-arbitrator/blob/master/doc/usage/tutorial.md), it turns out no pods are created.
The following format works fine.
```
apiVersion: arbitrator.incubator.k8s.io/v1alpha1
kind: QueueJob
metadata:
  namespace: default
  name: qj-01
spec:
  schedulingSpec:
    minAvailable: 1
  replicas: 3
  selector:
    matchLabels:
      queuejob.arbitrator.k8s.io: test
  template:
    metadata:
      labels:
        queuejob.arbitrator.k8s.io: test
      name: test
    spec:
      containers:
      - image: 172.16.1.41:5000/redis:3.0.5
        imagePullPolicy: IfNotPresent
        name: test
        resources:
          requests:
            cpu: "1"
            memory: 100Mi
      schedulerName: kar-scheduler

```
