### ISSUE TITLE
Schedulable job is pending if there is a non-scheduable job submitted prior to it

### ISSUE THREAD

**Issue by zionwu** [kubernetes-retired/kube-batch#561]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
I have k8s cluster with 6 worker nodes. 3 nodes are with 32 cpu, 3 nodes are with 40 cpu. 
I deployed the kube-batch to the cluster with default configuration:
```
  containers:
  - args:
    - --logtostderr
    - --v
    - "3"
    - --enable-namespace-as-queue
    image: kubesigs/kube-batch:v0.3
```

There is two jobs:
job1:
``` yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  backoffLimit: 6
  completions: 6
  parallelism: 6
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: job1
    spec:
      containers:
      - image: busybox
        args:
        - sleep
        - "30"
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: "35"
      restartPolicy: Never
      schedulerName: kube-batch
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: job1
spec:
  minMember: 4

```

job2:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: job2
spec:
  backoffLimit: 6
  completions: 6
  parallelism: 6
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: job2
    spec:
      containers:
      - image: busybox
        args:
        - sleep
        - "30"
        imagePullPolicy: IfNotPresent
        name: nginx
        resources:
          requests:
            cpu: "35"
      restartPolicy: Never
      schedulerName: kube-batch
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: job2
spec:
  minMember: 3
```
If I submit job1 alone, the job will always be pending as expected, as there is no enough resource for it.
If I submit job2 alone, the job can run successfully as expected, as there is enough resource for it.

If I submit job1 first, then submit job2 in the same namespace,  both jobs remain pending. If I delete job1,  job2 start running.

If I submit job1 first, then submit job2 in the different namespace,  both jobs remain pending. If I delete job1,  job2 start running.

**What you expected to happen**:
I think job2 should be running even job1 is in the same queue. 
As there is no enough resource for job1 but there is enough resource for job2.

**How to reproduce it (as minimally and precisely as possible)**:
First submit job1, then submit job2.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):   
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

```
- Cloud provider or hardware configuration:
bare metal machines. 
6 workers, 3 with 32 cpus, 3 with 40 cpus.

- OS (e.g. from /etc/os-release):
CentOS 7.3

- Kernel (e.g. `uname -a`):
3.10.0-514.el7.x86_64
