### ISSUE TITLE
Support plugin arguments

### ISSUE THREAD

**Issue by k82cn** [kubernetes-retired/kube-batch#637]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

Currently, we only support configuration on plugin's callback; it's better to support customized arguments to plugins. For example:

```yaml
actions: "reclaim, allocate, backfill, preempt"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
    arguments:
    - affinity.weight: 2
```

**Comment by k82cn** [comment]
@thandayuthapani , would you help on that?

**Comment by thandayuthapani** [comment]
@k82cn we can handle arguments as map instead of parameters being slice, since those parameters can have different keys for different plugins. affinity.weight might be only suitable for nodeorder plugin. So we can handle it as map, so in code we can try to get it from map.

**Comment by thandayuthapani** [comment]
Expected YAML should of this form, arguments are handled as map instead of slice.
```
actions: "reclaim, allocate, backfill, preempt"
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
    arguments:
      affinity.weight: 2
      affinity.enable: true
```
