### ISSUE TITLE
[Question] how to check the logs when i create A kube-batch job.

### ISSUE THREAD

**Issue by zoux86** [kubernetes-retired/kube-batch#664]
I installed the kube-batch V0.4.1 in my local k8s cluster recently， And i want to run the example given by the https://github.com/kubernetes-sigs/kube-batch/blob/master/doc/usage/tutorial.md
but the pod is alaways pending. 

here is the yaml
```
apiVersion: batch/v1
kind: Job
metadata:
  name: qj-1
spec:
  backoffLimit: 6
  completions: 6
  parallelism: 6
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: qj-1
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        resources:
          requests:
            cpu: "1"
      restartPolicy: Never
      schedulerName: kube-batch
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: qj-1
spec:
  minMember: 6
```

After i created the yaml , it showed:
![image](https://user-images.githubusercontent.com/14087435/55001225-16471700-500f-11e9-9733-30b8a80c2f80.png)
but the pod is always pending.
![image](https://user-images.githubusercontent.com/14087435/55001283-3a0a5d00-500f-11e9-8e45-9c3da6815751.png)

i used the   "kubectl  describe pod " and "kubectl logs " command , but still have no idea what wrong.

### so i want to know how to see the logs  when kube-batch Schedule a job. Can anyone  give me some advice?
 
**Anything else we need to know?**:
The result of  "kubectl describe pod" command:
![image](https://user-images.githubusercontent.com/14087435/55001970-b18cbc00-5010-11e9-93a3-437e19fac975.png)

**Environment**:
- Kubernetes version (use `kubectl version`):  1.13.4
1 master 3 node

- OS (e.g. from /etc/os-release):  ubuntu 16.04 
- kube-batch version: V0.4.1
