### ISSUE TITLE
[Question] Install kube-batch without helm

### ISSUE THREAD

**Issue by qw2208** [kubernetes-retired/kube-batch#900]
> /kind feature

**What happened**:
Is there a way to install kube-batch without helm? Helm may be too heavy.

**Comment by k82cn** [comment]
You can start it as normal port with enough permission :)

**Comment by qw2208** [comment]
Could you please give some more detailed instructions? I am not sure where to start.,

**Comment by xial-thu** [comment]
I prefer kustomize ^_^

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-batch
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kube-batch
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/binding", "events", "pods/status"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["scheduling.sigs.dev"]
  resources: ["podgroups", "queues"]
  verbs: ["*"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["*"]
- apiGroups: ["scheduling.incubator.k8s.io"]
  resources: ["queues", "podgroups"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kube-batch
subjects:
- kind: ServiceAccount
  name: kube-batch
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kube-batch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.sigs.dev
spec:
  group: scheduling.sigs.dev
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight:
              format: int32
              type: integer
          type: object
        status:
          properties:
            unknown:
              format: int32
              type: integer
            pending:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.sigs.dev
spec:
  group: scheduling.sigs.dev
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minMember:
              format: int32
              type: integer
            queue:
              type: string
            priorityClassName:
              type: string
          type: object
        status:
          properties:
            succeeded:
              format: int32
              type: integer
            failed:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha2
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: queues.scheduling.incubator.k8s.io
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: Queue
    plural: queues
  scope: Cluster
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            weight:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.incubator.k8s.io
spec:
  group: scheduling.incubator.k8s.io
  names:
    kind: PodGroup
    plural: podgroups
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            minMember:
              format: int32
              type: integer
            queue:
              type: string
            priorityClassName:
              type: string
          type: object
        status:
          properties:
            succeeded:
              format: int32
              type: integer
            failed:
              format: int32
              type: integer
            running:
              format: int32
              type: integer
          type: object
      type: object
  version: v1alpha1
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: Queue
metadata:
  name: default
spec:
  weight: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-batch
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-batch
  template:
    metadata:
      labels:
        app: kube-batch
    spec:
      serviceAccountName: kube-batch
      containers:
      - name: kube-batch
        image: xxxxxxx
        args: ["--logtostderr", "--v", "3"]
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 2048Mi
          requests:
            cpu: 2000m
            memory: 2048Mi
```
