### ISSUE TITLE
My kube-batch can t  read the configuration file

### ISSUE THREAD

**Issue by b675987273** [kubernetes-retired/kube-batch#923]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
I think it is a bug. 

**What happened**:
We can see the log. 
```shell
Failed to read scheduler configuration '/root/lijunhui/kube-batch/example/kube-batch-conf.yaml', using default configuration: open /root/lijunhui/kube-batch/example/kube-batch-conf.yaml: no such file or directory
```
But the file exicts.  

**What you expected to happen**:
This log will never exict.  

**How to reproduce it (as minimally and precisely as possible)**:
You can have a try with the following deployment yaml.
```yaml
...
containers:
      - args:
        - --logtostderr
        - --v
        - "3"
        - --scheduler-conf=/root/lijunhui/kube-batch/example/kube-batch-conf.yaml
        image: docker.cambricon.com/library/kubesigs/kube-batch:v0.5
...
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):1.14
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):Linux machine34 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:
