### ISSUE TITLE
A list of actions instead of hacky string spliting on schedulerConf

### ISSUE THREAD

**Issue by edwardstudy** [kubernetes-retired/kube-batch#945]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
```
actions: "allocate, backfill"
tiers:
- plugins:
  - name: priority
  - name: gang
- plugins:
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
```
https://github.com/kubernetes-sigs/kube-batch/blob/519821ef8ed04232a5f471c1b547de592082c71d/pkg/scheduler/util.go#L32-L41

We had a string to define actions. Why not use list like `tiers`.

**What you expected to happen**:
schedulerConf becomes:

```
actions:
- allocate
- backfill
tiers:
- plugins:
  - name: priority
  - name: gang
- plugins:
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
```

**How to reproduce it (as minimally and precisely as possible)**:
None

**Anything else we need to know?**:
None
**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
None
